name: 'p81'

on:
  push:
  #   branches:
  #   - main

jobs:
  deploy:
    name: 'deploy'
    runs-on: ubuntu-20.04

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      p81ENV: ${{ vars.p81ENV }}
    steps:
    - name: Update package lists
      run: sudo apt-get update
    - name: Install unzip
      run: sudo apt-get install unzip

    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install the latest version of Terragrunt CLI and configure the Terragrunt CLI configuration file with a Terragrunt Cloud user API token
    - name: Setup Terraform v1.3.7
      uses: hashicorp/setup-Terraform@v1
      with:
        terraform_version: 1.3.7
        terraform_wrapper: false
    - name: Setup Terraform version
      run: terraform --version
    - name: Setup Terraform wrapper path
      run: which terraform

    - name: Setup Terragrunt version 0.35.16
      uses: autero1/action-terragrunt@v1.1.0
      with:
        terragrunt_version: 0.35.16
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Export Environment Variables
      run: |
        CLOUDFRONT_URL=test002
        BUCKET_ID=test003
        echo "CLOUDFRONT_URL=$CLOUDFRONT_URL" >> $GITHUB_ENV
        echo "BUCKET_ID=$BUCKET_ID" >> $GITHUB_ENV
    # Initialize a new or existing Terragrunt working directory by creating initial files, loading any remote state, downloading modules, etc.
    # - name: Debug Environment Variables
    #   run: |
    #     echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
    #     echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
    #     echo "AWS_REGION: $AWS_REGION"
    #     echo "P81ENV: $P81ENV"


    # - name: Terragrunt Init in dev environment
    #   run: terragrunt init --terragrunt-non-interactive
    #   working-directory: ./terraform/environments/dev
  
    # - name: Terragrunt plan
    #   run: terragrunt run-all plan --terragrunt-non-interactive
    #   working-directory: ./terraform/environments/dev

  run_python_script:
    name: Run Python Script
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Use Environment Variables in Next Stage
        run: |
            echo "CLOUDFRONT_URL: $CLOUDFRONT_URL"
            echo "BUCKET_ID: $BUCKET_ID"

      # - name: Checkout code
      #   uses: actions/checkout@v2

  #     - name: Set up Python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.8'

  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install requests boto3

  #     - name: Execute Python script
  #       run: python path/to/your/python/script.py
